version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'TEAM6'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - sql_db:/var/lib/mysql
  backend:
    image: backend
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - '4000:3000'
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - '3000:3000'
      - '80:80'
volumes:
  sql_db:
